apiVersion: apps/v1
kind: Deployment
metadata:
  name: midnightuber
spec:
  replicas: 2
  selector:
    matchLabels:
      si3mshady: midnightuber
  template:
    metadata:
      labels:
        si3mshady: midnightuber
    spec:
      containers:
      - name: midnightuber
        image: si3mshady/blockchain-uber-clone:1
        resources:
          requests:
            cpu: .5 #half of the 1/4 CPU 
          limits:
            cpu: .25  #1/4 CPU = 250m
        ports:
        - containerPort: 3000
          hostPort: 3000
--- 
apiVersion: v1
kind: Service
metadata: 
  name: midnightuber
spec: 
  ports: 
    - port: 3000
      targetPort: 3000     
      nodePort: 30007
  selector: 
    si3mshady: midnightuber
  type: NodePort

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: midnightuber
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 20  # use less than 20 percent of the REQUESTED cpu for a pod 